// Package seerrApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package seerrApi

// MediaType defines values for GetBlocklistResponseResultsMediaType.
type MediaType string

// Defines values for MediaType.
const (
	MediaTypeMovie MediaType = "movie"
	MediaTypeTv    MediaType = "tv"
)

// PageInfo defines model for PageInfo.
type PageInfo struct {
	Pages    int `json:"pages,omitempty"`
	PageSize int `json:"pageSize,omitempty"`
	Results  int `json:"results,omitempty"`
	Page     int `json:"page,omitempty"`
}

// User defines model for User.
type User struct {
	/*Avatar            *string  `json:"avatar,omitempty"`
	CreatedAt         *string  `json:"createdAt,omitempty"`
	Email             *string  `json:"email,omitempty"`*/
	Id int `json:"id,omitempty"`
	/*JellyfinAuthToken *string  `json:"jellyfinAuthToken,omitempty"`
	Permissions       *float32 `json:"permissions,omitempty"`
	PlexToken         *string  `json:"plexToken,omitempty"`
	PlexUsername      *string  `json:"plexUsername,omitempty"`
	RequestCount      *float32 `json:"requestCount,omitempty"`
	UpdatedAt         *string  `json:"updatedAt,omitempty"`
	UserType          *int     `json:"userType,omitempty"`
	Username          *string  `json:"username,omitempty"`*/
}

type GetBlocklistResponse struct {
	PageInfo PageInfo `json:"pageInfo,omitempty"`
	Results  []struct {
		//CreatedAt *string  `json:"createdAt,omitempty"`
		//Id        *float32 `json:"id,omitempty"`
		MediaType MediaType `json:"mediaType,omitzero"`
		//Title     *string  `json:"title,omitempty"`
		TmdbId int `json:"tmdbId,omitzero"`
		//User   *User `json:"user,omitzero"`
	} `json:"results,omitzero"`
}

// Defines values for GetBlocklistParamsFilter.
const (
	GetBlocklistParamsFilterAll             string = "all"
	GetBlocklistParamsFilterBlocklistedTags string = "blocklistedTags"
	GetBlocklistParamsFilterManual          string = "manual"
)

// PostBlocklistJSONRequestBody defines body for PostBlocklist for application/json ContentType.
type PostBlocklistJSONRequestBody struct {
	TmdbId    int       `json:"tmdbId,omitzero"`
	MediaType MediaType `json:"mediaType,omitzero"`
	Title     string    `json:"title,omitzero"`
	User      int       `json:"user,omitempty"`
}
