// Code generated by goxmlstruct. DO NOT EDIT.

package AnimeList

type Anime struct {
	/*Anidbid           int     `xml:"anidbid,attr"`
	Defaulttvdbseason *string `xml:"defaulttvdbseason,attr"`
	Episodeoffset     *int    `xml:"episodeoffset,attr"`
	Imdbid            *string `xml:"imdbid,attr"`*/
	//Tmdbid            *string `xml:"tmdbid,attr"` // movie
	/*Tmdboffset        *int    `xml:"tmdboffset,attr"`
	Tmdbseason        *string `xml:"tmdbseason,attr"`*/
	Tmdbtv int `xml:"tmdbtv,attr,omitzero"`
	/*Tvdbid            string  `xml:"tvdbid,attr"`
	Before            *string `xml:"before"`
	MappingList       *struct {
		Mapping []struct {
			Anidbseason int    `xml:"anidbseason,attr"`
			End         *int   `xml:"end,attr"`
			Offset      *int   `xml:"offset,attr"`
			Start       *int   `xml:"start,attr"`
			Tmdbseason  *int   `xml:"tmdbseason,attr"`
			Tvdbseason  *int   `xml:"tvdbseason,attr"`
			CharData    string `xml:",chardata"`
		} `xml:"mapping"`
	} `xml:"mapping-list"`*/
	Name string `xml:"name,omitzero"`
	/*SupplementalInfo []struct {
		Replace  *bool   `xml:"replace,attr"`
		Credits  *string `xml:"credits"`
		Director *string `xml:"director"`
		Fanart   *struct {
			Thumb struct {
				Colors   string `xml:"colors,attr"`
				Dim      string `xml:"dim,attr"`
				Preview  string `xml:"preview,attr"`
				CharData string `xml:",chardata"`
			} `xml:"thumb"`
		} `xml:"fanart"`
		Genre  []string `xml:"genre"`
		Studio *string  `xml:"studio"`
	} `xml:"supplemental-info"`*/
}

type AnimeList struct {
	Anime []Anime `xml:"anime"`
}